
from database import (
    get_conn,
    fetch_all,
    fetch_one,
    fetch_val,
    execute,
    transaction,
    check_user_exists,
    check_document_exists,
    get_document_basic_info,
)

from .validation import (
    validate_uuid,
    validate_required_string,
    validate_user_id,
    validate_document_id,
    validate_document_reference,
    validate_rejection_reason,
    validate_document_type_acronym,
    validate_email,
    validate_pagination_params,
    validate_document_signers
)

from .utils import (
    generate_uuid,
    generate_document_number,
    format_datetime,
    format_date,
    parse_datetime,
    safe_json_loads,
    safe_json_dumps,
    clean_string,
    normalize_text,
    calculate_offset,
    calculate_total_pages,
    truncate_text,
    CustomJSONEncoder
)

from .exceptions import (
    GDIBaseException,
    ValidationError,
    BusinessLogicError,
    DatabaseError,
    AuthorizationError,
    NotFoundError,
    ConflictError,
    ExternalServiceError,
    DocumentNotFoundError,
    DocumentStateError,
    DocumentPermissionError,
    DocumentAlreadySignedError,
    DocumentAlreadyRejectedError,
    InvalidSignatureOrderError,
    NumeratorRequiredError,
    UserNotFoundError,
    UserInactiveError,
    exception_to_http_exception,
    handle_database_error,
    handle_exceptions,
    ErrorTypes,
    ErrorMessages
)

__all__ = [
    "get_conn",
    "fetch_all",
    "fetch_one",
    "fetch_val",
    "execute",
    "transaction",
    "check_user_exists",
    "check_document_exists",
    "get_document_basic_info",

    "validate_uuid",
    "validate_required_string",
    "validate_user_id",
    "validate_document_id",
    "validate_document_reference",
    "validate_rejection_reason",
    "validate_document_type_acronym",
    "validate_email",
    "validate_pagination_params",
    "validate_document_signers",

    "generate_uuid",
    "generate_document_number",
    "format_datetime",
    "format_date",
    "parse_datetime",
    "safe_json_loads",
    "safe_json_dumps",
    "clean_string",
    "normalize_text",
    "calculate_offset",
    "calculate_total_pages",
    "truncate_text",
    "CustomJSONEncoder",

    "GDIBaseException",
    "ValidationError",
    "BusinessLogicError",
    "DatabaseError",
    "AuthorizationError",
    "NotFoundError",
    "ConflictError",
    "ExternalServiceError",
    "DocumentNotFoundError",
    "DocumentStateError",
    "DocumentPermissionError",
    "DocumentAlreadySignedError",
    "DocumentAlreadyRejectedError",
    "InvalidSignatureOrderError",
    "NumeratorRequiredError",
    "UserNotFoundError",
    "UserInactiveError",
    "exception_to_http_exception",
    "handle_database_error",
    "handle_exceptions",
    "ErrorTypes",
    "ErrorMessages"
]
